name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "tennymic" --password-stdin
        docker image build . --file Dockerfile --tag tennymic/notegen
        docker push tennymic/notegen
